name: release

on:
  push:
    branches:
      - alpha
      - beta
      - master
    tags:
      - '!*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]') && ! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  release:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm i

      - name: Test
        run: npm test

      - name: Release Test
        run: npm run release -- --dry-run
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{github.token}}

      - name: Release
        run: npm run release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{github.token}}
